create table
  public.potions (
    sku text not null,
    name text not null default 'NULL'::text,
    inventory integer null default 0,
    price integer null default 50,
    num_red_ml integer null,
    num_green_ml integer null,
    num_blue_ml integer null,
    num_dark_ml integer null,
    constraint potions_pkey primary key (sku)
  ) tablespace pg_default;

create table
  public.global_inventory (
    num_red_ml integer null,
    gold integer not null,
    num_green_ml integer null default 0,
    num_blue_ml integer null default 0,
    num_dark_ml integer null,
    constraint global_inventory_pkey primary key (gold)
  ) tablespace pg_default;

create table
  public.cart_item (
    cart_id integer generated by default as identity,
    potion_sku text not null,
    quantity integer null,
    constraint cart_item_pkey primary key (cart_id),
    constraint cart_item_potion_sku_fkey foreign key (potion_sku) references potions (sku)
  ) tablespace pg_default;

  create table
  public.cart (
    cart_id integer generated by default as identity,
    name text not null,
    total_cost integer null,
    num_potions integer null,
    constraint cart_pkey primary key (cart_id),
    constraint cart_cart_id_fkey foreign key (cart_id) references cart_item (cart_id)
  ) tablespace pg_default;